WebApplication1_category_product_buyer-master/WebApplication2/Controllers/ÜrünController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models.Entity;


namespace WebApplication2.Controllers
{
    public class ÜrünController : Controller
    {
        // GET: Ürün
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.tabloürünler select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.ürünadi.Contains(p));
            }
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult YeniÜrün()
        {
            List<SelectListItem> degerler = (from i in db.tablokategoriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.kategoriad,
                                                 Value = i.kategoriid.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;             
            return View();
        }

        [HttpPost]
        public ActionResult YeniÜrün(tabloürünler p1)
        {
            var ktg = db.tablokategoriler.Where(m => m.kategoriid == p1.tablokategoriler.kategoriid).FirstOrDefault();
            p1.tablokategoriler = ktg;
            db.tabloürünler.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult sil(int id)
        {
            var urun = db.tabloürünler.Find(id);
            db.tabloürünler.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urun = db.tabloürünler.Find(id);
            List<SelectListItem> degerler = (from i in db.tablokategoriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.kategoriad,
                                                 Value = i.kategoriid.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View("UrunGetir", urun);
        }

        public ActionResult Guncelle(tabloürünler p1)
        {
            var urun = db.tabloürünler.Find(p1.ürünid);
            urun.ürünadi = p1.ürünadi;
            urun.marka = p1.marka;
           // urun.ürünkategori = p1.ürünkategori;
            urun.fiyat = p1.fiyat;
            urun.stok = p1.stok; 

            var ktg = db.tablokategoriler.Where(m => m.kategoriid == p1.tablokategoriler.kategoriid).FirstOrDefault();
            urun.ürünkategori = ktg.kategoriid;

            db.SaveChanges();
            return RedirectToAction("Index");


        }



    }
}

WebApplication1_category_product_buyer-master/WebApplication2/Views/Ürün/Index.cshtml
@using WebApplication2.Models.Entity
@model List<tabloürünler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using (Html.BeginForm("Index", "Ürün", FormMethod.Get))
{
    <p>
        <b> Aranacak Ürün Adı:</b> @Html.TextBox("p")
        <input type="submit" name="" value="Ara" />

    </p>
}


<table class="table table-bordered">
    <tr>
        <th>ÜRÜN ID</th>
        <th>ÜRÜN ADI</th>
        <th>MARKASI</th>
        <th>KATEGORİ</th>
        <th>FİYAT</th>
        <th>STOK</th>
    </tr>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <th>@urn.ürünid</th>
                <td>@urn.ürünadi</td>
                <td>@urn.marka</td>
                <td>@urn.tablokategoriler.kategoriad</td>
                <td>@urn.fiyat</td>
                <td>@urn.stok</td>
                <td>
                    @Html.ActionLink("SİL", "sil", new { id = urn.ürünid }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek istiyor musunuz')" })
                @*<a href="/Ürün/sil/@urn.ürünid" class="btn btn-danger">SİL</a>*@
            </td>
            <td><a href="/Ürün/UrunGetir/@urn.ürünid" class="btn btn-success">GÜNCELLE</a></td>

        </tr>
    }

    </tbody>


</table>
<a href="/Ürün/YeniÜrün/" class="btn btn-primary">Yeni Ürün Ekle</a>

WebApplication1_category_product_buyer-master/WebApplication2/Views/Ürün/UrunGetir.cshtml
@model WebApplication2.Models.Entity.tabloürünler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using (Html.BeginForm("Guncelle", "Ürün", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Ürün ID")
    @Html.TextBoxFor(m => m.ürünid, new { @class = "form-control" })
    <br />
    @Html.Label("ÜRÜN ADI")
    @Html.TextBoxFor(m => m.ürünadi, new { @class = "form-control" })
    <br />
    @Html.Label("MARKA")
    @Html.TextBoxFor(m => m.marka, new { @class = "form-control" })
    <br />
    @Html.Label("KATAGORİ")
   @Html.DropDownListFor(m=>m.tablokategoriler.kategoriid,(List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />
    @Html.Label("FİYAT")
    @Html.TextBoxFor(m => m.fiyat, new { @class = "form-control" })
    <br />
    @Html.Label("STOK")
    @Html.TextBoxFor(m => m.stok, new { @class = "form-control" })



</div>
<div>
    <button class="btn btn-warning">Ürün Güncelle</button>
</div>
}

WebApplication1_category_product_buyer-master/WebApplication2/Views/Ürün/YeniÜrün.cshtml
@model WebApplication2.Models.Entity.tabloürünler
@{
    ViewBag.Title = "YeniÜrün";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="ürünadi" value="" required="" placeholder="Ürün Adını Yazınız"/>

    </div>
    <div>
        <label>Marka</label>
        <input type="text" class="form-control" name="marka" value="" required="" placeholder="Markasını Yazınız"/>

    </div>

    <div>
        <label>Kategori</label>
        @Html.DropDownListFor(m=>m.tablokategoriler.kategoriid,(List<SelectListItem>)ViewBag.dgr, new { @class="form-control"})

    </div>
    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="fiyat" value="" required="" placeholder="Fiyatını Yazınız"/>

    </div>
    <div>
        <label>Stok</label>
        <input type="text" class="form-control" name="stok" value="" required="" placeholder="Stok Adedini Yazınız"/>

    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Ürün Ekle</button>
    </div>



</form>