WebApplication1_category_product_buyer-master/WebApplication2/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models.Entity;

namespace WebApplication2.Controllers
{
    public class MusteriController : Controller
    {
        MvcDbStokEntities db = new MvcDbStokEntities();
        // GET: Musteri
        public ActionResult Index(string p)
        {
            var degerler = from d in db.tablomüsteriler select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.müsteriad.Contains(p));
            }
            return View(degerler.ToList());
        //     var degerler = db.tablomüsteriler.ToList();
        //    return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {

            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(tablomüsteriler p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.tablomüsteriler.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult sil(int id)
        {
            var musteri = db.tablomüsteriler.Find(id);
            db.tablomüsteriler.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var mus = db.tablomüsteriler.Find(id);
            return View("MusteriGetir", mus);
        }

        public ActionResult Guncelle(tablomüsteriler p1)
        {
            var musteri = db.tablomüsteriler.Find(p1.müsteriid);
            musteri.müsteriad = p1.müsteriad;
            musteri.müsterisoyad = p1.müsterisoyad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication1_category_product_buyer-master/WebApplication2/Views/Musteri/Index.cshtml
@using WebApplication2.Models.Entity
@model List<tablomüsteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
            {
<p>
    <b> Aranacak Müşteri Adı:</b> @Html.TextBox("p")
    <input type="submit" name="" value="Ara" />

</p>
            }



<table class="table table-bordered">
    <tr>
        <th>MÜŞTERİ ID</th>
        <th>MÜŞTERİ ADI</th>
        <th>MÜŞTERİ SOYADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>


    </tr>
    <tbody>
        @foreach (var mst in Model)
        {
        <tr>
            <th>@mst.müsteriid</th>
            <td>@mst.müsteriad</td>
            <td>@mst.müsterisoyad</td>
            <td>@Html.ActionLink("SİL", "sil", new { id = mst.müsteriid }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek istiyor musunuz')" })</td>
            <td><a href="/Musteri/MusteriGetir/@mst.müsteriid" class="btn btn-success">GÜNCELLE</a></td>

        </tr>
            }

    </tbody>


</table>
<a href="/Musteri/YeniMusteri/" class="btn btn-primary">Yeni Müşteri Ekle</a>

WebApplication1_category_product_buyer-master/WebApplication2/Views/Musteri/MusteriGetir.cshtml
@model WebApplication2.Models.Entity.tablomüsteriler
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("MÜŞTERİ ID")
    @Html.TextBoxFor(m => m.müsteriid, new { @class = "form-control" })
    <br />
    @Html.Label("MÜŞTERİ ADI")
    @Html.TextBoxFor(m => m.müsteriad, new { @class = "form-control" })
    <br />
    @Html.Label("MÜŞTERİ SOYADI")
    @Html.TextBoxFor(m => m.müsterisoyad, new { @class = "form-control" })
</div>
    <div>
        <button class="btn btn-warning">Müşteri Güncelle</button>
    </div>
}
            

WebApplication1_category_product_buyer-master/WebApplication2/Views/Musteri/YeniMusteri.cshtml
@model WebApplication2.Models.Entity.tablomüsteriler
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<form class="form-group" method="post">

    <div>
        <label>Müşteri Adı</label>
       
            @Html.TextBoxFor(m => m.müsteriad, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.müsteriad, "", new { @style = "color:red" })

    </div>


    <div>
        <label>Müşteri Soyadı</label>
        @Html.TextBoxFor(m => m.müsterisoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.müsterisoyad, "", new { @style = "color:red" })


    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Müşteri Ekle</button>
    </div>



</form>