WebApplication2_ajax_begin_name_city-master/WebApplication1/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExampleDBEntities : DbContext
    {
        public ExampleDBEntities()
            : base("name=ExampleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
    }
}

WebApplication2_ajax_begin_name_city-master/WebApplication1/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\aysu.terzi\Desktop\çalışma denemeler\mvc denemeleri\WebApplication1\WebApplication1\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

WebApplication2_ajax_begin_name_city-master/WebApplication1/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string City { get; set; }
    }
}

WebApplication2_ajax_begin_name_city-master/WebApplication1/Controllers/AjaxBeginController.cs
using WebApplication1.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;

namespace WebApplication1.Controllers
{
    public class AjaxBeginController : Controller
    {
        // GET: AjaxBegin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {

            UserCreateViewModel model = new UserCreateViewModel();
            return View(model);
        }
        [HttpPost]
        public JsonResult Create(UserCreateViewModel model)
        {
            Thread.Sleep(3000);

            JsonResultModel jModel = new JsonResultModel();
            try
            {
                WebApplication1.Models.ExampleDBEntities db = new Models.ExampleDBEntities();
                WebApplication1.Models.Users userModel = new Models.Users();
                userModel.UserName = model.UserName;
                userModel.UserSurname = model.UserSurname;
                userModel.City = model.City;
                db.Users.Add(userModel);
                db.SaveChanges();
                jModel.IsSuccess = true;
                jModel.UserMessage = "Kayıt Başarıyla Gerçekleşti.";
            }
            catch (Exception ex)
            {
                jModel.IsSuccess = false;
                jModel.UserMessage = "Kayıt Gerçekleşemedi. Hata: " + ex.Message;
            }
            return Json(jModel, JsonRequestBehavior.AllowGet);
            
        }

    }
}

WebApplication2_ajax_begin_name_city-master/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication2_ajax_begin_name_city-master/WebApplication1/Views/AjaxBegin/Create.cshtml
@model WebApplication1.ViewModel.UserCreateViewModel
@{
    ViewBag.Title = "Create";
}



<br />
@using (Ajax.BeginForm("Create", "AjaxBegin", FormMethod.Post, new AjaxOptions { OnSuccess = "success", LoadingElementId = "loading" })) //onsuccess: formumuz başarılı bir şekilde gitti verileri aldı ve geri döndüyse bu method çalışacak success adında js fonksiyonu yazıcaz
{
<div class="container">
    <div class="row justify-content-center">
        <div style="background-color:lightseagreen; width:auto; height:auto">
            <div class="col col-auto" style="border-color: black; border-style:dotted; padding: 20px;  margin: 20px;">
                <h2>Yeni Kullanıcı</h2>
                <p style="margin-bottom:5px;">Ad:</p>
                @Html.TextBoxFor(m => m.UserName)
                <br />
                @Html.ValidationMessageFor(m => m.UserName, "", new { @style = "color:red" })

                <p style="margin-bottom:5px;">Soyad:</p>
                @Html.TextBoxFor(m => m.UserSurname)
                <br />
                @Html.ValidationMessageFor(m => m.UserSurname, "", new { @style = "color:red" })

                <p style="margin-bottom:5px;">Şehir:</p>
                @Html.TextBoxFor(m => m.City)
                <br />
                @Html.ValidationMessageFor(m => m.City, "", new { @style = "color:red" })

                <div class="col-auto" style=" margin-top:20px;">
                    <input type="submit" value="Kaydet" />
                </div>
                <div id="loading" style="display:none">
                    <br />
                    Kaydediliyor............
                </div>
                <br />
                <div id="userMessage"> </div>

            </div>
        </div>
    </div>
</div>

<div class="container">

  </div>




    }

    @section scripts
{
        <script type="text/javascript">
            function success(result) {
                if (result.IsSuccess == true) {
                    $("form")[0].reset();
                }
                $("#userMessage").html(result.UserMessage);
            }

            
        </script>
    }

WebApplication2_ajax_begin_name_city-master/WebApplication1/Views/AjaxBegin/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col col-auto" style="padding: 20px;  margin: 20px;">
            <a class="btn btn-info" href="/AjaxBegin/Create"> Yeni Kullanıcı</a>
        </div>
    </div>
</div>

WebApplication2_ajax_begin_name_city-master/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication2_ajax_begin_name_city-master/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()


    @Scripts.Render("~/bundles/jquery")

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)
  
</body>
</html>